Informasjonsforvaltning/concept-catalog-gui

src/components/field-array-source/field-array-source.component.tsx
src/components/new-concept-button/new-concept-button.scss

fix: Changed color on new-source-button and title relationToSource

---

src/api/concept-catalogue-api.ts
src/api/concept-registration-api.ts
src/api/publisher-api.ts
src/config.ts
src/index.tsx
src/pages/concept-list-page/concept-list-resolver.tsx

…no tests that would benefit from it

refaktorering før utvikling på host

---

src/l10n/helptexts.nb.ts

Kan dere hjelpe meg å oppdatere snapshots samtidig som review på denne?

fixed minor text bug

---

src/components/status-bar/status-bar.component.tsx
src/pages/concept-registration-page/concept-registration-page-pure.tsx
src/pages/concept-registration-page/form-concept/form-concept-pure.component.tsx
src/pages/concept-registration-page/form-concept/form-concept.component.tsx

Refactor: flytte statusbar inn i Form.
Gjøre initial validation av form, gi verdi som prop til Statusbar.
Vise / ikke vise publish knapp avhengig av om initial er validert.

fix: ikke vise publish knapp ved initial hvis skjema invalid

---

src/components/fields/field-input/field-input-pure.component.tsx
src/components/fields/field-textarea/field-textarea-pure.component.tsx
src/pages/concept-registration-page/form-concept/form-concept-pure.component.tsx
src/pages/concept-registration-page/form-concept/form-concept.component.tsx

Closes Informasjonsforvaltning/fdk-issue-tracker#320

fix: shows initial errors in form

---

package-lock.json
package.json
src/api/concept-catalogue-api.ts
src/app/reducers/conceptMapper.ts
src/components/error-row/index.tsx
src/components/error-row/styled.ts
src/domain/Common.ts
src/domain/ImportError.ts
src/l10n/nb.ts
src/pages/concept-list-page/concept-list-page-pure.tsx
src/pages/concept-registration-page/form-concept/form-concept.schema.ts

feat: improve concept validation

---

src/components/fields/field-datepicker/field-datepicker-pure.component.tsx

Legger til dato på format yyyy-MM-dd som er samme format det sjekkes for i Yup.

fix(field-datepicker-pure): change date format to be validated

---

package-lock.json
src/l10n/nb.ts
src/pages/concept-list-page/concept-list/components/concept-list-collapse-item/index.tsx
src/pages/concept-list-page/concept-list/components/concept-list-collapse-item/styled.ts
src/pages/concept-list-page/concept-list/components/concept-list-header/index.tsx
src/pages/concept-list-page/concept-list/components/concept-list-header/styled.ts
src/pages/concept-list-page/concept-list/components/concept-list-item/index.tsx
src/pages/concept-list-page/concept-list/components/concept-list-item/styled.ts
src/pages/concept-list-page/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-list-page/concept-list/components/concept-list/index.tsx
src/types/domain.d.ts
src/types/enums.ts
src/utils/sort/index.ts

feat: adds last modified time field

---

src/pages/concept-list-page/concept-list/components/concept-list-collapse-item/index.tsx

fix: display most recent date for collapse item

---

src/app/reducers/conceptMapper.ts

Sette initiell status på importert begrep

fix: set initial status when importing concepts

---

src/app/routeConfig.ts

feat: hide overview-page from breadcrumbs

---

src/l10n/nb.ts

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/558

fix: typo nynorks changed to nynorsk

---

README.md
src/app/routeConfig.ts
src/pages/concept-list-page-beta/concept-list-page-pure.tsx
src/pages/concept-list-page-beta/concept-list-page.ts
src/pages/concept-list-page-beta/concept-list-resolver.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list-collapse-item/index.tsx
src/pages/concept-list-page-beta/concept-list/components/concept-list-collapse-item/styled.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list-header/index.tsx
src/pages/concept-list-page-beta/concept-list/components/concept-list-header/styled.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list-item/index.tsx
src/pages/concept-list-page-beta/concept-list/components/concept-list-item/styled.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-list-page-beta/concept-list/components/concept-list/concept-list.component.test.tsx
src/pages/concept-list-page-beta/concept-list/components/concept-list/index.tsx
src/pages/concept-list-page-beta/concept-list/index.ts
src/pages/concept-list-page-beta/concept-list/utils/concepts.ts
src/pages/concept-list-page-beta/concept-list/utils/determine-validity.ts
src/pages/concept-list-page-beta/concept-title/concept-title.component.tsx
src/pages/concept-list-page-beta/concept-title/styled.ts
src/pages/concept-list-page-beta/styled.ts

resolves https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/470
The page which is under development can reached by adding /beta at the end of the URL.
eks: http://localhost:8203/910244132/beta

feat: feature toggler for landing page

---

src/pages/concept-registration-page/form-concept/related-concepts/related-concepts.component.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/732

fix: some concept not showing

---

src/l10n/helptexts.nb.ts
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/term/source/source-pure.component.tsx
src/pages/concept-registration-page/form-concept/term/source/source.component.ts
src/pages/concept-registration-page/form-concept/term/term.component.tsx
src/types/domain.d.ts

Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/555

feat: public and specialist definisjon

---

README.md
src/app/reducers/conceptMapper.ts
src/l10n/helptexts.nb.ts
src/mock/concepts.json
src/pages/concept-list-page-beta/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-list-page/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-registration-page/form-concept/use-of-concept/useOfConcept.component.tsx

Feat/jr/remove bruksområde

---

src/l10n/helptexts.nb.ts
src/pages/concept-registration-page/form-concept/form-concept.schema.ts
src/pages/concept-registration-page/form-concept/term/term.component.tsx

Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/560

feat: change text definitions

---

src/components/form-control/index.tsx

fix: handle patch error

---

src/components/breadcrumbs/breadcrumbs.component.tsx
src/config.ts

fix: catalog frontend feature toggle

---

src/components/fields/field-checkbox-tree/field-checkbox-tree-pure.component.tsx
src/l10n/nb.ts

Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/568

feat: add filter search to checkbox tree and set expanded

---

README.md
src/api/catalog-admin-api/users.ts
src/api/concept-catalog-api.ts
src/app/reducers/conceptMapper.ts
src/features/users/index.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list-collapse-item/index.tsx
src/pages/concept-list-page-beta/concept-list/components/concept-list-item/index.tsx
src/pages/concept-list-page/concept-list/components/concept-list-collapse-item/index.tsx
src/pages/concept-list-page/concept-list/components/concept-list-item/index.tsx
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/internal-info/index.tsx
src/pages/concept-registration-page/form-concept/internal-info/styled.ts
src/types/domain.d.ts
src/types/enums.ts

related to https://github.com/Informasjonsforvaltning/concept-catalog/issues/229

feat: support for choosing assignedUser from dropdown

---

src/components/fields/field-checkbox-tree/field-checkbox-tree-pure.component.tsx
src/features/code-lists/index.ts
src/l10n/nb.ts
src/lib/patchConceptForm.ts
src/pages/concept-list-page/concept-list/components/concept-list-collapse-item/index.tsx
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/internal-info/index.tsx
src/pages/concept-registration-page/form-concept/use-of-concept/useOfConcept.component.tsx
src/pages/concept-registration-page/form-concept/utils/index.ts
src/types/domain.d.ts
src/utils/code-list/index.ts

feat: subject codes

---

src/components/form-control/index.tsx
src/pages/concept-registration-page/form-concept/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/745

fix: handle unsaved changes

---

package-lock.json
src/pages/concept-registration-page/form-concept/form-concept.schema.ts

fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/576

fix: make extra definitions optional

---

src/api/concept-catalog-api.ts
src/components/form-control/index.tsx
src/features/conceptForm/index.ts
src/l10n/helptexts.nb.ts
src/lib/concept/index.ts
src/lib/patchConceptForm.ts
src/lib/validateConceptForm.ts
src/pages/concept-list-page-beta/concept-list/components/concept-list/index.tsx
src/pages/concept-list-page-beta/concept-list/utils/concepts.ts
src/pages/concept-list-page/concept-list/components/concept-list/index.tsx
src/pages/concept-registration-page/concept-registration-page-pure.tsx
src/pages/concept-registration-page/form-concept/form-concept.schema.ts
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/internal-info/index.tsx
src/pages/concept-registration-page/form-concept/internal-info/styled.ts
src/pages/concept-registration-page/form-concept/utils/index.ts
src/types/domain.d.ts

FIxes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/579
Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/580

Feat  abreviation / Feat new concept without presave

---

src/app/reducers/conceptMapper.ts
src/mock/concepts.json
src/pages/concept-list-page-beta/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-list-page/concept-list/components/concept-list/__snapshots__/concept-list.component.test.tsx.snap
src/pages/concept-registration-page/form-concept/form-concept.schema.ts
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/utils/index.ts
src/types/domain.d.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/754

fix: merknad and eksempel type should be string

---

package-lock.json
src/l10n/helptexts.nb.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/805

fix: use latest spec links

---

package-lock.json
package.json
src/pages/concept-list-page-beta/concept-list-page-pure.tsx
src/pages/concept-list-page/concept-list-page-pure.tsx
src/pages/concept-registration-page/concept-registration-page-pure.tsx

Fixes https://github.com/Informasjonsforvaltning/concept-catalog/issues/292

fix: use default status DRAFT and disable deprecated create

---

package-lock.json
src/components/breadcrumbs/breadcrumbs.component.tsx
src/l10n/nb.ts

fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/596

feat: add to detail page link

---

package-lock.json
package.json
src/pages/concept-registration-page/form-concept/form-concept.schema.ts

Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/615

fix: version should be min 0.1.0

---

src/l10n/helptexts.nb.ts
src/l10n/nb.ts
src/pages/concept-registration-page/form-concept/form-concept.schema.ts
src/pages/concept-registration-page/form-concept/index.tsx
src/pages/concept-registration-page/form-concept/validity/validity.component.tsx
src/types/domain.d.ts

feat: add replace by unpusblished concept field in form

---

audit-resolve.json
package-lock.json
src/l10n/nb.ts
src/pages/concept-registration-page/form-concept/related-concepts/components/relation/index.tsx

closes [#918](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/918)

chore: update text assosiative relation description

---

package-lock.json
package.json
src/utils/code-list/index.ts

closes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/660

fix: nodes with parent not found in accumulator got misplaced
